// Run against local development only, with an explicitly supplied test admin.
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import process from 'node:process'

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const origin = process.env.AUTH_SMOKE_ORIGIN || 'http://127.0.0.1:5173'
assert.ok(['127.0.0.1', 'localhost'].includes(new URL(origin).hostname))
const fixture = JSON.parse(await readFile(process.env.AUTH_SMOKE_FIXTURE, 'utf8'))
const password = `Violet boats ${randomUUID()}!`
const replacement = `Crimson stones ${randomUUID()}!`
const email = `phasef-${randomUUID()}@example.com`
const results = []
const pass = label => { results.push(label); console.log(`PASS ${label}`) }
const browser = await chromium.launch({ headless: true })
const context = await browser.newContext({ baseURL: origin, reducedMotion: 'reduce' })
const adminContext = await browser.newContext({ baseURL: origin, reducedMotion: 'reduce' })
const page = await context.newPage()
const admin = await adminContext.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
admin.on('pageerror', error => errors.push(error.message))
const post = (ctx, path, data) => ctx.request.post(`/api${path}`, { data, headers: { Origin: origin } })
async function login(target, name, secret, next = '/app/profile') {
  await target.goto(`/login?next=${encodeURIComponent(next)}`)
  await target.getByLabel('Email or username', { exact: true }).fill(name)
  await target.getByLabel('Password', { exact: true }).fill(secret)
  await target.getByRole('button', { name: 'Sign in', exact: true }).click()
}
let accountId
try {
  const caps = await (await context.request.get('/api/auth/capabilities')).json()
  assert.equal(caps.signup, true)
  assert.equal(caps.admin_recovery, true)
  assert.equal(caps.google, false)
  if (process.env.AUTH_SMOKE_UI_ONLY !== '1') {
  await page.goto('/signup')
  await page.getByLabel('Full name', { exact: true }).fill('Browser Test')
  await page.getByLabel('Work email', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByLabel('Confirm password', { exact: true }).fill(password)
  assert.equal(await page.getByRole('combobox').count(), 0)
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await page.getByRole('status').filter({ hasText: 'Request received' }).waitFor()
  pass(`signup (${caps.signup_mode}); no role selector`)
  const duplicate = await post(context, '/auth/signup', { display_name: 'Browser Test', email: ` ${email.toUpperCase()} `, password })
  assert.equal(duplicate.status(), 202)
  assert.equal((await duplicate.json()).status, 'accepted')
  await login(admin, fixture.username, fixture.password, '/app/admin')
  await admin.waitForURL('**/app/admin')
  const rows = await (await adminContext.request.get('/api/admin/users?limit=100')).json()
  const accounts = rows.filter(row => row.email === email)
  assert.equal(accounts.length, 1)
  accountId = accounts[0].id
  assert.equal(accounts[0].role, 'requester')
  assert.equal(accounts[0].signup_pending, caps.signup_mode === 'approval')
  pass('normalized duplicate creates no second account')
  if (caps.signup_mode === 'approval') {
    assert.equal((await post(context, '/auth/login', { username: email, password })).status(), 401)
    await admin.getByRole('row').filter({ hasText: email }).getByRole('button', { name: 'Approve', exact: true }).click()
    await admin.getByRole('row').filter({ hasText: email }).getByRole('cell', { name: 'Active', exact: true }).waitFor()
    pass('pending login rejected; admin approval')
  }
  await login(page, email, 'wrong-password')
  await page.getByRole('alert').filter({ hasText: 'Incorrect email' }).waitFor()
  pass('wrong password rejected')
  await login(page, email.toUpperCase(), password)
  await page.waitForURL('**/app/profile')
  await page.getByRole('heading', { name: 'Active sessions' }).waitFor()
  const user = await (await context.request.get('/api/auth/me')).json()
  assert.equal(user.email, email)
  assert.equal(user.display_name, 'Browser Test')
  assert.deepEqual(user.linked_identities, [])
  const cookies = await context.cookies()
  assert.ok(cookies.some(cookie => cookie.httpOnly && cookie.sameSite === 'Lax'))
  await page.reload()
  await page.getByRole('heading', { name: 'Active sessions' }).waitFor()
  pass('email login; intended route; HttpOnly session survives refresh; profile')
  const oldSession = await browser.newContext({ baseURL: origin, storageState: await context.storageState() })
  await page.getByRole('button', { name: 'Sign out', exact: true }).last().click()
  await page.waitForURL(url => url.pathname === '/login')
  assert.equal((await context.request.get('/api/auth/me')).status(), 401)
  pass('logout revokes cookie session')
  await oldSession.close()
  await login(page, 'dev_requester', 'dev-requester-pass-1')
  await page.waitForURL('**/app/profile')
  await page.getByRole('button', { name: 'Sign out', exact: true }).last().click()
  await page.waitForURL(url => url.pathname === '/login')
  pass('preserved legacy username login')
  await login(page, email, password)
  await page.waitForURL('**/app/profile')
  const beforeReset = await browser.newContext({ baseURL: origin, storageState: await context.storageState() })
  await page.goto('/forgot-password')
  if (!caps.email_recovery) {
    await page.getByRole('note').filter({ hasText: 'Email recovery is not available' }).waitFor()
    assert.equal(await page.getByRole('button', { name: 'Send recovery code' }).isDisabled(), true)
    pass('SMTP disabled: honest offline/admin recovery')
  }
  await admin.getByRole('row').filter({ hasText: email }).getByRole('button', { name: 'Issue recovery code' }).click()
  const recoveryNotice = admin.getByRole('status').filter({ hasText: 'One-time recovery code' })
  await recoveryNotice.waitFor()
  const code = (await recoveryNotice.innerText()).match(/\b\d{6}\b/)[0]
  await page.goto('/verify-otp')
  await page.getByLabel('Email or username', { exact: true }).fill(email)
  await page.getByLabel('6-digit code', { exact: true }).fill(code === '000000' ? '000001' : '000000')
  await page.getByRole('button', { name: 'Verify code' }).click()
  await page.getByRole('alert').filter({ hasText: 'invalid or has expired' }).waitFor()
  await page.getByLabel('6-digit code', { exact: true }).fill(code)
  await page.getByRole('button', { name: 'Verify code' }).click()
  await page.waitForURL('**/reset-password')
  await page.getByLabel('New password', { exact: true }).fill(replacement)
  await page.getByLabel('Confirm new password', { exact: true }).fill(replacement)
  await page.getByRole('button', { name: 'Update password' }).click()
  await page.waitForURL(url => url.pathname === '/login')
  await page.getByRole('status').filter({ hasText: 'Password updated' }).waitFor()
  assert.equal((await beforeReset.request.get('/api/auth/me')).status(), 401)
  await beforeReset.close()
  assert.equal((await post(context, '/auth/login', { username: email, password })).status(), 401)
  await login(page, email, replacement)
  await page.waitForURL('**/app/profile')
  pass('real admin OTP; invalid code; reset redirect; old password and sessions invalidated')
  await admin.getByRole('row').filter({ hasText: email }).getByRole('combobox').selectOption('reviewer')
  await page.reload()
  await page.waitForURL(url => url.pathname === '/login')
  await login(page, email, replacement)
  await page.waitForURL('**/app/profile')
  assert.equal((await (await context.request.get('/api/auth/me')).json()).role, 'reviewer')
  await admin.getByRole('row').filter({ hasText: email }).getByRole('button', { name: 'Revoke sessions' }).click()
  await page.reload()
  await page.waitForURL(url => url.pathname === '/login')
  await admin.getByRole('row').filter({ hasText: email }).getByRole('button', { name: 'Deactivate', exact: true }).click()
  await admin.getByRole('row').filter({ hasText: email }).getByRole('cell', { name: 'Inactive', exact: true }).waitFor()
  assert.equal((await post(context, '/auth/login', { username: email, password: replacement })).status(), 401)
  await admin.getByRole('row').filter({ hasText: email }).getByRole('button', { name: 'Activate', exact: true }).click()
  await admin.getByRole('row').filter({ hasText: email }).getByRole('cell', { name: 'Active', exact: true }).waitFor()
  pass('admin role, session revocation, deactivation and activation')
  await page.goto('/auth/callback?status=success')
  await page.getByRole('note').filter({ hasText: 'Google sign-in is not enabled' }).waitFor()
  await page.goto('/login')
  assert.equal(await page.getByRole('link', { name: 'Continue with Google' }).count(), 0)
  pass('Google unavailable without credentials; callback cannot fabricate login')
  }
  // Provider-free UI checks only. No SMTP delivery or live Google login is claimed.
  const ui = await browser.newContext({ baseURL: origin, reducedMotion: 'reduce' })
  let uiCaps = { ...caps, email_recovery: true, google: true }
  await ui.route('**/api/auth/capabilities', route => route.fulfill({ json: uiCaps }))
  let requests = 0
  await ui.route('**/api/auth/password/forgot', route => {
    requests += 1
    return route.fulfill({ status: 202, json: { status: 'accepted', message: 'If eligible, instructions will be provided.' } })
  })
  const uiPage = await ui.newPage()
  await uiPage.goto('/forgot-password')
  await uiPage.getByLabel('Work email').fill('synthetic@example.com')
  await uiPage.getByRole('button', { name: 'Send recovery code' }).click()
  await uiPage.getByRole('status').filter({ hasText: 'eligible verified account' }).waitFor()
  await uiPage.getByRole('link', { name: 'Enter recovery code' }).click()
  assert.equal(await uiPage.getByLabel('Email or username', { exact: true }).inputValue(), 'synthetic@example.com')
  assert.equal(await uiPage.getByRole('button', { name: /Resend in/ }).isDisabled(), true)
  assert.equal(requests, 1)
  await uiPage.goto('/login')
  assert.equal(await uiPage.getByRole('link', { name: 'Continue with Google' }).getAttribute('href'), '/api/auth/google/start')
  await uiPage.goto('/auth/callback?status=pending_or_inactive')
  await uiPage.getByRole('status').filter({ hasText: 'approval or activation' }).waitFor()
  await uiPage.goto('/auth/callback?status=failed')
  await uiPage.getByRole('status').filter({ hasText: 'could not be completed' }).waitFor()
  uiCaps = { ...uiCaps, signup: false, signup_mode: 'disabled' }
  await uiPage.goto('/signup')
  await uiPage.getByRole('note').filter({ hasText: 'Self-service sign-up is not enabled' }).waitFor()
  assert.equal(await uiPage.locator('#signup-name').isDisabled(), true)
  await ui.close()
  pass('deterministic UI: forgot response, OTP handoff, resend cooldown, Google link/errors, disabled signup')
  assert.deepEqual(errors, [])
  pass('no browser runtime errors')
} finally {
  if (accountId) await post(adminContext, `/admin/users/${accountId}/deactivate`)
  await writeFile(process.env.AUTH_SMOKE_REPORT || 'auth-smoke-results.json', JSON.stringify({ results, errors }, null, 2))
  await browser.close()
}
